services:

  karma8_s3:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_ADDRESS: ":8080"
      PART_SIZE_THRESHOLD: 1048576
      MINIO_ENDPOINTS: "nginx:9000"
      MINIO_ACCESS_KEY: "minioadmin"
      MINIO_SECRET_KEY: "minioadmin"
      MINIO_USE_SSL: "false"
      MINIO_BUCKET_NAME: "files"
    depends_on:
      - nginx
    networks:
      - minio-cluster
    restart: always

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "9000:9000"
    depends_on:
      - minio1
      - minio2
      - minio3
      - minio4
      - minio5
      - minio6
    networks:
      - minio-cluster

  minio1:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio1-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "10001:9001"

  minio2:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio2-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "12001:9001"

  minio3:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio3-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "13001:9001"

  minio4:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio4-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "14001:9001"

  minio5:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio5-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "15001:9001"

  minio6:
    image: minio/minio
    command: server --console-address ":9001" http://minio{1...6}/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio6-data:/data
    networks:
      - minio-cluster
    expose:
      - "9000"
      - "9001"
    ports:
      - "16001:9001"

volumes:
  minio1-data:
  minio2-data:
  minio3-data:
  minio4-data:
  minio5-data:
  minio6-data:

networks:
  minio-cluster:
